[project]
name = "alphafold-decoded"
version = "0.1.0"
requires_python = ">=3.11"
description = "Tutorial code for implementing AlphaFold2 from scratch."

dependencies = [
    "torch",
    "torchvision",
    "numpy>=2.4",
    "matplotlib",
    "modelcif",
    "py3Dmol",
    "transformers",
    "datasets",
    "lightning",
    "ipykernel",
    "nbformat",
    "nbconvert",
]